data durability and consistency
athensresearch/athens-backend pull request #2
Opened 2021-04-24 13:51 UTC by arkRedM

2021-04-24 13:55 UTC, agentydragon requested changes
maybe add tests?

2021-04-24 13:55 UTC, agentydragon commented on src/clj/athens_sync/core.clj
> -                  :port (env :nrepl-port)}))
revert?

2021-04-24 13:55 UTC, agentydragon commented on src/clj/athens_sync/datsync_utils.clj
> +;; assumption db-before is always correct
these checks look useful enough to share with Athens client / tests

2021-04-24 13:55 UTC, agentydragon commented on src/clj/athens_sync/datsync_utils.clj
> +(defn gen-block-uid
this is probably also duplicated with Athens code.

fine to keep for now, I guess, but just more bits speaking in favor of merging the repos.

2021-04-24 13:58 UTC, arkRedM commented on src/clj/athens_sync/core.clj
> -                  :port (env :nrepl-port)}))
Before merge

2021-04-24 13:58 UTC, arkRedM commented on src/clj/athens_sync/datsync_utils.clj
> +;; assumption db-before is always correct
Still thinking about the data flow. Not finalized

2021-04-27 19:28 UTC, neotyk commented on src/clj/athens_sync/core.clj
> -                  :port (env :nrepl-port)}))
Best to use parsed command line args for it.

2021-04-29 04:49 UTC, tangjeff0 commented
Please use https://github.com/athensresearch/athens/discussions/1082 for discussion, because it includes both frontend and backend.

2021-05-17 10:11 UTC, arkRedM commented on src/clj/athens_sync/datsync_utils.clj
> +(defn gen-block-uid
https://github.com/athensresearch/athens/issues/840#issuecomment-831695838

2021-05-18 12:52 UTC, arkRedM commented on src/clj/athens_sync/datsync_utils.clj
> +;; assumption db-before is always correct
what do you have in mind for the test strategy?
Consider: Multiple apps and keeping backend is probably a round-about way to test. Localizing invariant test will not much value without rtc check

2021-05-18 12:53 UTC, arkRedM commented on src/clj/athens_sync/datsync_utils.clj
> +(defn gen-block-uid
Probably keeping it separate for now. Not seeing much reason to merge repos

2021-05-18 13:22 UTC, agentydragon commented on src/clj/athens_sync/datsync_utils.clj
> +;; assumption db-before is always correct
test strategy for these invariants? I'd write individual unit tests that these invariants fail as expected when broken.

I agree that the invariant test is more useful in the backend than in the frontend, because the backend has more opportunities to break the database.

It might be useful in the client for, say, debugging. If someone is experiencing some issue with their database, they'd run Athens with `--debug` flag and that would make Athens check these invariants as pre & post-conditions of some operations.

But really the heuristic why I think this should be in shared code is because of how I think about monorepos. If you have 2 binaries `A` and `B` that share some code, with folders, say, `/binary_a`, `/binary_b` and `/common`, I'd put this into `/common` because it's code that only depends on there being a database, which both binaries have.

2021-05-18 14:49 UTC, arkRedM commented on src/clj/athens_sync/datsync_utils.clj
> +;; assumption db-before is always correct
debug mode doesn't sounds right. These invariants will run on every txn. Not just debug mode. Maybe I miscommunicated the logic here.

2021-05-18 14:58 UTC, agentydragon commented on src/clj/athens_sync/datsync_utils.clj
> +;; assumption db-before is always correct
I was talking about the client, not the server. If we want, we can also test those invariants on the client on every tx. I talked about a separate mode in case any of those checks were expensive.

2021-05-24 15:18 UTC, tangjeff0 commented
Closing based on dependent PR from Athens frontend https://github.com/athensresearch/athens/pull/1075#issuecomment-846014933

2021-05-24 15:18 UTC, closed without merging